"use strict";
/* NextGen Digital Academy — Public Engine /frontend/main.js */
const NEXTGEN_KEYS={courses:"nextgen_courses",blogs:"nextgen_blogs",comments:"nextgen_comments",dbVersion:"nextgen_db_version"};
const DEFAULT_DB={version:"6.0.0",courses:[
{id:"google-ads-mastery",title:"Master Google Ads",shortTitle:"Google Ads",category:"ads",categoryLabel:"Paid Ads",level:"Beginner to Advanced",duration:"4 Weeks",instructor:"Shahzad Hassan",description:"Launch profitable Google Search campaigns for leads, calls, sales, and local service businesses.",standardPrice:99,vipPrice:199,oldVipPrice:199,mentorshipPrice:199,discount:"90% Off for 1 Month",badge:"High Intent",featured:true,gradient:"linear-gradient(135deg,#102f5f,#05122b 58%,#0a2144)"},
{id:"facebook-sales-funnels",title:"FB Sales Funnels",shortTitle:"FB Funnels",category:"funnels",categoryLabel:"Funnels",level:"Intermediate",duration:"5 Weeks",instructor:"Shahzad Hassan",description:"Build Facebook ad funnels that convert cold Pakistani traffic into qualified leads and buyers.",standardPrice:99,vipPrice:149,oldVipPrice:149,mentorshipPrice:199,discount:"90% Off for 1 Month",badge:"Conversion",featured:true,gradient:"linear-gradient(135deg,#111b4d,#05122b 55%,#12376b)"},
{id:"mentorship-funnels",title:"Mentorship Funnels",shortTitle:"Mentorship",category:"mentorship",categoryLabel:"Mentorship",level:"Advanced",duration:"6 Weeks",instructor:"Shahzad Hassan",description:"Create premium coaching and mentorship funnels with trust, proof, offer strategy, and closing systems.",standardPrice:99,vipPrice:199,oldVipPrice:199,mentorshipPrice:199,discount:"90% Off for 1 Month",badge:"Premium",featured:true,gradient:"linear-gradient(135deg,#071936,#020716 55%,#102f5f)"},
{id:"tiktok-ads-growth",title:"TikTok Ads Growth",shortTitle:"TikTok Ads",category:"ads",categoryLabel:"Paid Ads",level:"Beginner",duration:"3 Weeks",instructor:"Shahzad Hassan",description:"Use short-form creatives and TikTok ads to generate attention, leads, and sales.",standardPrice:79,vipPrice:129,oldVipPrice:179,mentorshipPrice:179,discount:"Launch Offer",badge:"Trending",featured:false,gradient:"linear-gradient(135deg,#05243d,#05122b 55%,#12376b)"},
{id:"landing-page-mastery",title:"Landing Page Mastery",shortTitle:"Landing Pages",category:"funnels",categoryLabel:"Funnels",level:"Intermediate",duration:"4 Weeks",instructor:"Shahzad Hassan",description:"Design landing pages with hooks, proof, urgency, offers, and WhatsApp conversion flow.",standardPrice:89,vipPrice:149,oldVipPrice:199,mentorshipPrice:199,discount:"90% Off for 1 Month",badge:"CRO",featured:false,gradient:"linear-gradient(135deg,#0a2144,#05122b 58%,#062c55)"},
{id:"whatsapp-closing-system",title:"WhatsApp Closing System",shortTitle:"WhatsApp Sales",category:"business",categoryLabel:"Online Business",level:"Beginner to Intermediate",duration:"2 Weeks",instructor:"Shahzad Hassan",description:"Turn WhatsApp chats into paid enrollments using scripts, follow-ups, and proof.",standardPrice:49,vipPrice:99,oldVipPrice:149,mentorshipPrice:149,discount:"Student Special",badge:"Pakistan Ready",featured:false,gradient:"linear-gradient(135deg,#063c39,#05122b 58%,#0a2144)"},
{id:"seo-blog-authority",title:"SEO Blog Authority",shortTitle:"SEO Authority",category:"business",categoryLabel:"Online Business",level:"Intermediate",duration:"5 Weeks",instructor:"Shahzad Hassan",description:"Build search authority with topic clusters, helpful blogs, and conversion-focused SEO.",standardPrice:89,vipPrice:159,oldVipPrice:199,mentorshipPrice:199,discount:"90% Off for 1 Month",badge:"Organic Growth",featured:false,gradient:"linear-gradient(135deg,#0b2f4d,#05122b 58%,#102f5f)"},
{id:"agency-launch-blueprint",title:"Agency Launch Blueprint",shortTitle:"Agency Launch",category:"business",categoryLabel:"Online Business",level:"Advanced",duration:"6 Weeks",instructor:"Shahzad Hassan",description:"Start a digital agency with service offers, pricing, outreach, and delivery systems.",standardPrice:129,vipPrice:199,oldVipPrice:299,mentorshipPrice:299,discount:"Mentorship Deal",badge:"Business",featured:false,gradient:"linear-gradient(135deg,#102f5f,#030816 58%,#071936)"},
{id:"email-automation-mastery",title:"Email Automation Mastery",shortTitle:"Email Automation",category:"funnels",categoryLabel:"Funnels",level:"Intermediate",duration:"3 Weeks",instructor:"Shahzad Hassan",description:"Create nurture sequences that educate leads, build trust, and recover missed sales.",standardPrice:69,vipPrice:129,oldVipPrice:179,mentorshipPrice:179,discount:"Automation Offer",badge:"Follow-Up",featured:false,gradient:"linear-gradient(135deg,#071936,#05122b 55%,#0e3c77)"},
{id:"copywriting-for-sales",title:"Copywriting for Sales",shortTitle:"Copywriting",category:"business",categoryLabel:"Online Business",level:"Beginner to Advanced",duration:"4 Weeks",instructor:"Shahzad Hassan",description:"Write hooks, ad copy, landing page copy, and WhatsApp scripts that convert.",standardPrice:79,vipPrice:139,oldVipPrice:199,mentorshipPrice:199,discount:"90% Off for 1 Month",badge:"Sales Skill",featured:false,gradient:"linear-gradient(135deg,#152452,#05122b 58%,#102f5f)"},
{id:"youtube-growth-engine",title:"YouTube Growth Engine",shortTitle:"YouTube Growth",category:"business",categoryLabel:"Online Business",level:"Beginner",duration:"5 Weeks",instructor:"Shahzad Hassan",description:"Plan content, titles, thumbnails, and funnels that turn attention into business growth.",standardPrice:89,vipPrice:159,oldVipPrice:219,mentorshipPrice:219,discount:"Creator Offer",badge:"Creator",featured:false,gradient:"linear-gradient(135deg,#122e5c,#05122b 58%,#061832)"},
{id:"freelancing-client-acquisition",title:"Freelancing Client Acquisition",shortTitle:"Freelancing",category:"mentorship",categoryLabel:"Mentorship",level:"Beginner to Intermediate",duration:"4 Weeks",instructor:"Shahzad Hassan",description:"Find clients, pitch services, build proof, close deals, and create repeat income.",standardPrice:79,vipPrice:149,oldVipPrice:249,mentorshipPrice:249,discount:"Pakistan Student Deal",badge:"Career",featured:false,gradient:"linear-gradient(135deg,#082a46,#05122b 58%,#12376b)"}
],blogs:[
{id:"digital-marketing-pakistan",title:"Why Digital Marketing Is Exploding in Pakistan",tag:"Market Insight",date:"Latest",readTime:"5 min read",excerpt:"Pakistan’s online business economy is growing fast, but only skilled marketers can convert attention into income.",featured:true},
{id:"funnels-vs-websites",title:"Funnels vs Websites: What Actually Converts?",tag:"Funnels",date:"Guide",readTime:"4 min read",excerpt:"A beautiful website is not enough. Conversion comes from a guided path: hook, offer, trust, proof, and action.",featured:false},
{id:"google-ads-buyer-intent",title:"Google Ads and Buyer Intent",tag:"Paid Ads",date:"Strategy",readTime:"6 min read",excerpt:"Google Ads works because people are already searching. The skill is knowing which searches deserve your money.",featured:false},
{id:"pakistani-student-online-income",title:"The Real Online Income Path for Pakistani Students",tag:"Students",date:"Mentorship",readTime:"7 min read",excerpt:"Avoid random shortcuts. Build one monetizable skill, one offer, one audience, and one repeatable sales system.",featured:false},
{id:"whatsapp-sales-proof",title:"Why WhatsApp Proof Increases Course Sales",tag:"Sales Psychology",date:"Conversion",readTime:"4 min read",excerpt:"For Pakistani buyers, trust often happens inside WhatsApp. Screenshots, replies, and payment proof reduce hesitation.",featured:false}
],comments:[]};
const App={courses:[],blogs:[],comments:[],visibleCourseLimit:6,elements:{}};const $=s=>document.querySelector(s);
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function read(key,fb){try{const v=localStorage.getItem(key);return v?JSON.parse(v):fb}catch{return fb}}function write(key,val){try{localStorage.setItem(key,JSON.stringify(val))}catch{toast("Storage unavailable. Please check browser settings.")}}
function price(v){return `$${Number(v||0).toLocaleString("en-US")}`}function slow(){const c=navigator.connection||navigator.mozConnection||navigator.webkitConnection;return matchMedia("(max-width:760px)").matches||(c&&/2g|3g|slow-2g/i.test(c.effectiveType||""))}function debounce(fn,delay=180){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),delay)}}function toast(msg){const el=App.elements.toast;if(!el)return;el.textContent=msg;el.classList.remove("hidden");setTimeout(()=>el.classList.add("hidden"),2800)}
function seed(){if(!localStorage.getItem(NEXTGEN_KEYS.courses))write(NEXTGEN_KEYS.courses,DEFAULT_DB.courses);if(!localStorage.getItem(NEXTGEN_KEYS.blogs))write(NEXTGEN_KEYS.blogs,DEFAULT_DB.blogs);if(!localStorage.getItem(NEXTGEN_KEYS.comments))write(NEXTGEN_KEYS.comments,DEFAULT_DB.comments);if(!localStorage.getItem(NEXTGEN_KEYS.dbVersion))localStorage.setItem(NEXTGEN_KEYS.dbVersion,DEFAULT_DB.version)}
function load(){seed();App.courses=read(NEXTGEN_KEYS.courses,DEFAULT_DB.courses);App.blogs=read(NEXTGEN_KEYS.blogs,DEFAULT_DB.blogs);App.comments=read(NEXTGEN_KEYS.comments,[])}
function cache(){App.elements={year:$("#year"),navToggle:$("#navToggle"),navLinks:$("#navLinks"),courseGrid:$("#courseGrid"),courseSearch:$("#courseSearch"),courseFilter:$("#courseFilter"),blogGrid:$("#blogGrid"),commentForm:$("#commentForm"),commentName:$("#commentName"),commentEmail:$("#commentEmail"),commentMessage:$("#commentMessage"),commentList:$("#commentList"),toast:$("#toast")}}
function filteredCourses(){const q=App.elements.courseSearch?App.elements.courseSearch.value.toLowerCase().trim():"";const cat=App.elements.courseFilter?App.elements.courseFilter.value:"all";return App.courses.filter(c=>[c.title,c.shortTitle,c.category,c.categoryLabel,c.level,c.duration,c.instructor,c.description,c.badge].join(" ").toLowerCase().includes(q)&&(cat==="all"||c.category===cat))}
function card(c){return `<article class="course-card" data-course-id="${esc(c.id)}"><div class="course-thumb" style="background:${esc(c.gradient)};"><span class="course-category">${esc(c.categoryLabel||c.category)}</span><div style="position:absolute;inset:auto 1rem 1rem 1rem;z-index:2;"><strong style="display:block;max-width:78%;color:#fff;font-size:clamp(1.35rem,3vw,2rem);line-height:1.02;letter-spacing:-.04em;text-shadow:0 6px 18px rgba(0,0,0,.35);">${esc(c.shortTitle||c.title)}</strong><span style="display:inline-flex;margin-top:.55rem;padding:.28rem .62rem;border-radius:999px;color:#05122b;background:linear-gradient(135deg,#00afff,#39d8ff);font-size:.72rem;font-weight:900;text-transform:uppercase;letter-spacing:.04em;">${esc(c.badge||"NextGen")}</span></div></div><h3 class="course-title">${esc(c.title)}</h3><p class="course-desc">${esc(c.description)}</p><div class="course-meta"><span>${esc(c.level)}</span><span>${esc(c.duration)}</span><span>${esc(c.instructor||"Shahzad Hassan")}</span></div><div class="course-pricing"><div class="price-tier"><small>Standard</small><strong>${price(c.standardPrice)}</strong></div><div class="price-tier"><small>VIP</small><strong>${c.oldVipPrice?`<del>${price(c.oldVipPrice)}</del> `:""}${price(c.vipPrice)}</strong></div><div class="price-tier"><small>Mentorship</small><strong>${price(c.mentorshipPrice)}</strong></div></div><div class="discount-pill">${esc(c.discount)}</div><a href="#contact" class="course-cta btn" data-course-enroll="${esc(c.id)}">Start Reading Free ▶</a></article>`}
function renderCourses(reset=false){const grid=App.elements.courseGrid;if(!grid)return;if(reset)App.visibleCourseLimit=slow()?6:99;const all=filteredCourses();const visible=all.slice(0,App.visibleCourseLimit);if(!all.length){grid.innerHTML=`<div class="course-empty">No courses found. Try another search or category.</div>`;return}grid.innerHTML=visible.map(card).join("")+(visible.length<all.length?`<div class="course-empty" style="padding:1rem;"><button type="button" class="btn btn-primary" id="loadMoreCourses">Load More Courses</button></div>`:"")}
function renderBlogs(){const grid=App.elements.blogGrid;if(!grid)return;if(!App.blogs.length){grid.innerHTML=`<div class="course-empty">No insights published yet.</div>`;return}grid.innerHTML=App.blogs.map(b=>`<article class="blog-card ${b.featured?"featured":""}" data-blog-id="${esc(b.id)}"><div><div class="blog-meta"><span class="blog-tag">${esc(b.tag)}</span><span>${esc(b.date)}</span><span>${esc(b.readTime)}</span></div><h3 class="blog-title">${esc(b.title)}</h3><p class="blog-excerpt">${esc(b.excerpt)}</p><a href="#comments" class="blog-read-more">Read Insight →</a></div></article>`).join("")}
function newComment(n,e,m){return{id:`comment-${Date.now()}`,name:n,email:e,message:m,date:new Date().toLocaleDateString("en-PK",{year:"numeric",month:"short",day:"numeric"}),status:"pending",replies:[]}}
function renderComments(){const list=App.elements.commentList;if(!list)return;const approved=App.comments.filter(c=>c.status==="approved");const pin=`<div class="comment-bubble approved"><div class="comment-topline"><p class="comment-author">NextGen Team</p><span class="comment-date">Pinned</span></div><p class="comment-text">Welcome to the student discussion area. Approved comments will appear here after admin review.</p><span class="comment-status approved">Approved</span></div>`;list.innerHTML=pin+approved.map(c=>`<div class="comment-bubble approved"><div class="comment-topline"><p class="comment-author">${esc(c.name)}</p><span class="comment-date">${esc(c.date)}</span></div><p class="comment-text">${esc(c.message)}</p><span class="comment-status approved">Approved</span></div>${Array.isArray(c.replies)?c.replies.filter(r=>r.status==="approved").map(r=>`<div class="comment-bubble reply approved"><div class="comment-topline"><p class="comment-author">${esc(r.name||"NextGen Team")}</p><span class="comment-date">${esc(r.date||"")}</span></div><p class="comment-text">${esc(r.message)}</p><span class="comment-status approved">Approved</span></div>`).join(""):""}`).join("")}
function bind(){const e=App.elements;e.navToggle?.addEventListener("click",()=>e.navLinks.classList.toggle("open"));e.navLinks?.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>e.navLinks.classList.remove("open")));const re=debounce(()=>renderCourses(true));e.courseSearch?.addEventListener("input",re);e.courseFilter?.addEventListener("change",()=>renderCourses(true));e.commentForm?.addEventListener("submit",ev=>{ev.preventDefault();const n=e.commentName.value.trim(),em=e.commentEmail.value.trim(),m=e.commentMessage.value.trim();if(!n||!em||!m){toast("Please complete all comment fields.");return}App.comments.unshift(newComment(n,em,m));write(NEXTGEN_KEYS.comments,App.comments);e.commentForm.reset();toast("Comment submitted. It will appear after admin approval.")});document.addEventListener("click",ev=>{const more=ev.target.closest("#loadMoreCourses");if(more){App.visibleCourseLimit+=6;renderCourses(false);return}const en=ev.target.closest("[data-course-enroll]");if(en){const c=App.courses.find(x=>x.id===en.getAttribute("data-course-enroll"));if(c)toast(`Selected: ${c.title}. Continue on WhatsApp to enroll.`)}});window.addEventListener("storage",ev=>{if(!Object.values(NEXTGEN_KEYS).includes(ev.key))return;load();renderCourses(true);renderBlogs();renderComments()})}
function init(){cache();if(App.elements.year)App.elements.year.textContent=new Date().getFullYear();App.visibleCourseLimit=slow()?6:99;load();bind();renderCourses(true);renderBlogs();renderComments()}document.addEventListener("DOMContentLoaded",init);
